name: ${DEV_COMPOSE_PROJECT_NAME:-docker-l4d2-competitive-dev}

services:
  dev_comp:
    build:
      dockerfile: Dockerfile
      context: .
    image: dev_comp
    container_name: ${DEV_COMP_CONTAINER_NAME:-dev_comp}
    pull_policy: always
    env_file:
      - .env
      - .env.secrets
    volumes:
      - dev_comp_data:/data
    environment:
      - SSH_PORT=${SSH_PORT:-422}
      - L4D2_INSTALL=${L4D2_INSTALL:-skip}
      - L4D2_AUTOSTART=${L4D2_AUTOSTART:-false}
      - L4D2_UPDATER=${L4D2_UPDATER:-false}
      - STACK_PROFILE=${STACK_PROFILE:-default}
    ports:
      - "27015:27015"
      - "27115:27115"
      - "${SSH_PORT:-422}:${SSH_PORT:-422}"

volumes:
  dev_comp_data:
    name: ${DEV_COMP_DATA_VOLUME_NAME:-dev_comp_data}
