name: ${PROJECT_NAME:-docker-l4d2-competitive}

services:
  l4d2:
    build:
      dockerfile: Dockerfile
      context: .
    image: l4d2-dev
    container_name: ${CONTAINER_NAME:-l4d2}
    pull_policy: always
    env_file:
      - .env
      - .env.secrets
    volumes:
      - data:/data
    environment:
      - SSH_PORT=${SSH_PORT:-422}
      - L4D2_INSTALL=${L4D2_INSTALL:-normal}
      - L4D2_AUTOSTART=${L4D2_AUTOSTART:-true}
      - L4D2_UPDATER=${L4D2_UPDATER:-true}
      - STACK_PROFILE=${STACK_PROFILE:-default}
    ports:
      - "27015:27015"
      - "27115:27115"
      - "${SSH_PORT:-422}:${SSH_PORT:-422}"

volumes:
  data:
    name: ${DATA_VOLUME_NAME:-l4d2_data}
