name: ${COMPOSE_PROJECT_NAME:-docker-l4d2-competitive}

services:
  comp_l4d2:
    image: ghcr.io/aoc-gamers/lgsm-l4d2-competitive:${COMP_IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: ${COMP_CONTAINER_NAME:-comp_l4d2}
    pull_policy: always
    env_file:
      - .env
      - .env.secrets
    volumes:
      - comp_data:/data
    environment:
      - SSH_PORT=${SSH_PORT:-422}
      - SSH_KEY=${SSH_KEY}
      - STACK_PROFILE=${STACK_PROFILE:-latest}
    network_mode: host

volumes:
  comp_data:
    name: ${COMP_DATA_VOLUME_NAME:-comp_data}