#!/bin/bash
# env_stack.sh - Canonical runtime environment for the installer framework.

: "${DIR_APP:=/app}"
: "${DIR_INSTALLER:=/data/installer}"
: "${DIR_INSTALLER_BIN:=${DIR_INSTALLER}/bin}"
: "${DIR_INSTALLER_LIB:=${DIR_INSTALLER}/lib}"
: "${DIR_INSTALLER_CONFIG:=${DIR_INSTALLER}/config}"
: "${DIR_INSTALLER_STATE:=${DIR_INSTALLER}/state}"
: "${DIR_STACK:=/data/stack}"
: "${DIR_STACK_HOOKS:=${DIR_STACK}/hooks}"
: "${DIR_LEFT4DEAD2:=${LGSM_SERVERFILES:-/data/serverfiles}/left4dead2}"
: "${DIR_ADDONS:=${DIR_LEFT4DEAD2}/addons}"
: "${DIR_SOURCEMOD:=${DIR_ADDONS}/sourcemod}"
: "${DIR_CFG:=${DIR_LEFT4DEAD2}/cfg}"
: "${GAMESERVER:=l4d2server}"

export DIR_APP
export DIR_INSTALLER
export DIR_INSTALLER_BIN
export DIR_INSTALLER_LIB
export DIR_INSTALLER_CONFIG
export DIR_INSTALLER_STATE
export DIR_STACK
export DIR_STACK_HOOKS
export DIR_LEFT4DEAD2
export DIR_ADDONS
export DIR_SOURCEMOD
export DIR_CFG
export GAMESERVER

env_stack_dump() {
    cat <<EOF
DIR_APP=${DIR_APP}
DIR_INSTALLER=${DIR_INSTALLER}
DIR_INSTALLER_BIN=${DIR_INSTALLER_BIN}
DIR_INSTALLER_LIB=${DIR_INSTALLER_LIB}
DIR_INSTALLER_CONFIG=${DIR_INSTALLER_CONFIG}
DIR_INSTALLER_STATE=${DIR_INSTALLER_STATE}
DIR_STACK=${DIR_STACK}
DIR_STACK_HOOKS=${DIR_STACK_HOOKS}
DIR_LEFT4DEAD2=${DIR_LEFT4DEAD2}
DIR_ADDONS=${DIR_ADDONS}
DIR_SOURCEMOD=${DIR_SOURCEMOD}
DIR_CFG=${DIR_CFG}
GAMESERVER=${GAMESERVER}
EOF
}
