name: Docker Image Build and Push

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      # Condicional para construir la imagen de acuerdo a la rama
      - name: Build and push Docker image for develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/aoc-gamers/lgsm-l4d2-competitive:develop

      - name: Build and push Docker image for main
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/aoc-gamers/lgsm-l4d2-competitive:latest

      # Disparar webhook a Docker-L4D2-AoC dependiendo de la rama
      - name: Trigger AoC Workflow for develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          curl -X POST \
            https://api.github.com/repos/AoC-Gamers/Docker-L4D2-AoC/actions/workflows/docker-image.yml/dispatches \
            -H "Authorization: token ${{ secrets.TOKEN_WEBHOOCK }}" \
            -d '{"ref":"develop"}'

      - name: Trigger AoC Workflow for main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          curl -X POST \
            https://api.github.com/repos/AoC-Gamers/Docker-L4D2-AoC/actions/workflows/docker-image.yml/dispatches \
            -H "Authorization: token ${{ secrets.TOKEN_WEBHOOCK }}" \
            -d '{"ref":"main"}'
