name: Construcción y Publicación de Imagen Docker

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Construir y publicar imagen Docker para develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/aoc-gamers/lgsm-l4d2-competitive:develop

      - name: Construir y publicar imagen Docker para main
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/aoc-gamers/lgsm-l4d2-competitive:latest

      - name: Activar Workflow AoC para develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          curl -X POST \
            https://api.github.com/repos/AoC-Gamers/Docker-L4D2-AoC/actions/workflows/docker-image.yml/dispatches \
            -H "Authorization: token ${{ secrets.TOKEN_WEBHOOK }}" \
            -d '{"ref":"develop"}'

      - name: Activar Workflow AoC para main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          curl -X POST \
            https://api.github.com/repos/AoC-Gamers/Docker-L4D2-AoC/actions/workflows/docker-image.yml/dispatches \
            -H "Authorization: token ${{ secrets.TOKEN_WEBHOOK }}" \
            -d '{"ref":"main"}'

      - name: Activar Workflow AoC Vanilla para develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          curl -X POST \
            https://api.github.com/repos/AoC-Gamers/Docker-L4D2-AoC-Vanilla/actions/workflows/docker-image.yml/dispatches \
            -H "Authorization: token ${{ secrets.TOKEN_WEBHOOK }}" \
            -d '{"ref":"develop"}'

      - name: Activar Workflow AoC Vanilla para main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          curl -X POST \
            https://api.github.com/repos/AoC-Gamers/Docker-L4D2-AoC-Vanilla/actions/workflows/docker-image.yml/dispatches \
            -H "Authorization: token ${{ secrets.TOKEN_WEBHOOK }}" \
            -d '{"ref":"main"}'
